"""create orders rate cards and agents

Revision ID: 6f372bd20f2a
Revises: b4bd353413aa
Create Date: 2026-08-22 23:18:24.585128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f372bd20f2a'
down_revision: Union[str, Sequence[str], None] = 'b4bd353413aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('tracking_number', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=False),
    sa.Column('pickup_address', sa.String(length=500), nullable=False),
    sa.Column('delivery_address', sa.String(length=500), nullable=False),
    sa.Column('delivery_pincode', sa.String(length=10), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('package_weight', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'ASSIGNED', 'PICKED_UP', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_delivery_pincode'), 'orders', ['delivery_pincode'], unique=False)
    op.create_index(op.f('ix_orders_tracking_number'), 'orders', ['tracking_number'], unique=True)
    op.create_index(op.f('ix_orders_zone_id'), 'orders', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_zone_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_tracking_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_delivery_pincode'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
