"""add rate cards

Revision ID: ff9c27410095
Revises: 0d38d2213e81
Create Date: 2026-08-23 00:23:10.050206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff9c27410095'
down_revision: Union[str, Sequence[str], None] = '0d38d2213e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_cards',
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('base_rate', sa.Integer(), nullable=False),
    sa.Column('rate_per_kg', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_cards_zone_id'), 'rate_cards', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_cards_zone_id'), table_name='rate_cards')
    op.drop_table('rate_cards')
    # ### end Alembic commands ###
